### ISSUE TITLE
Problemas con Chark

### ISSUE THREAD

**Issue by JoelFEscobar** [ULL-ESIT-INF-DSI-2122/ull-esit-inf-dsi-21-22-prct09-filesystem-notes-app-alu0101130408#1]
Buenas tardes @esegredo.
Estoy implementando la clase Note la cual especifica como será la estructura de la nota de un usuario, sin embargo al tratar de hacer las pruebas unitarias de esta clase. me da todo el rato el mismo error, buscando por internet recomiendan que quite la opcion de modules pero entonces no podria hacer importacion. Cito el error:

```
TypeError [ERR_UNKNOWN_FILE_EXTENSION]: Unknown file extension ".ts" for /home/usuario/ull-esit-inf-dsi-21-22-prct09-filesystem-notes-app-alu0101130408/tests/notes.spec.ts
    at new NodeError (node:internal/errors:371:5)
    at Object.getFileProtocolModuleFormat [as file:] (node:internal/modules/esm/get_format:84:11)
    at defaultGetFormat (node:internal/modules/esm/get_format:99:38)
    at defaultLoad (node:internal/modules/esm/load:21:14)
    at ESMLoader.load (node:internal/modules/esm/loader:359:26)
    at ESMLoader.moduleProvider (node:internal/modules/esm/loader:280:58)
    at new ModuleJob (node:internal/modules/esm/module_job:66:26)
    at ESMLoader.#createModuleJob (node:internal/modules/esm/loader:297:17)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:261:34)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:337:24)
    at async importModuleDynamicallyWrapper (node:internal/vm/module:437:15)
    at async formattedImport (/home/usuario/ull-esit-inf-dsi-21-22-prct09-filesystem-notes-app-alu0101130408/node_modules/mocha/lib/nodejs/esm-utils.js:7:14)
    at async Object.exports.requireOrImport (/home/usuario/ull-esit-inf-dsi-21-22-prct09-filesystem-notes-app-alu0101130408/node_modules/mocha/lib/nodejs/esm-utils.js:48:32)
    at async Object.exports.loadFilesAsync (/home/usuario/ull-esit-inf-dsi-21-22-prct09-filesystem-notes-app-alu0101130408/node_modules/mocha/lib/nodejs/esm-utils.js:103:20)
    at async singleRun (/home/usuario/ull-esit-inf-dsi-21-22-prct09-filesystem-notes-app-alu0101130408/node_modules/mocha/lib/cli/run-helpers.js:125:3)
    at async Object.exports.handler (/home/usuario/ull-esit-inf-dsi-21-22-prct09-filesystem-notes-app-alu0101130408/node_modules/mocha/lib/cli/run.js:374:5)
```

No se a que puede deberse, puesto que leyendo la documentación que usted proporciono en el guión de la práctica en esta clase solo uso el modulo de chark y esta bien usado tal y como figura en los diversos ejemplos.

Un saludo y gracias de antemano.

**Comment by esegredo** [comment]
Estás utilizando la última versión del paquete chalk (cuya major version es la 5). Dicha versión es un paquete ESM puro y vas a tener problemas a la hora de utilizarlo con TypeScript.

Tal y como he indicado en el nuevo guión de la práctica, deben usar la versión 4.1.2 (la última de la major version 4) que si que es compatible con TypeScript.

Saludos.
